# Generated by Django 2.2 on 2020-04-13 12:27

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='enumeratedList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('subtitle', models.CharField(blank=True, max_length=50)),
                ('text', wagtail.core.fields.RichTextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('linkText', models.CharField(blank=True, max_length=100)),
                ('linkUrl', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.URLField(blank=True, null=True)),
                ('description', models.CharField(max_length=50)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
        ),
        migrations.CreateModel(
            name='iconItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=50)),
                ('text', wagtail.core.fields.RichTextField(blank=True)),
                ('linkText', models.CharField(max_length=50)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='socialMediaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.URLField(blank=True, null=True)),
                ('icon', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='testimonialItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('testimonial', wagtail.core.fields.RichTextField(blank=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
        ),
        migrations.AddField(
            model_name='homepage',
            name='blog_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='blog_title',
            field=models.CharField(blank=True, default='Blogs', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='blurb_background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='blurb_header',
            field=models.CharField(blank=True, default='Blurb', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='blurb_subheader',
            field=models.CharField(blank=True, default='this is a blurb', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='blurb_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='client_addressLine1',
            field=models.CharField(blank=True, default='Line 1', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='client_addressLine2',
            field=models.CharField(blank=True, default='Line 2', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='client_country',
            field=models.CharField(blank=True, default='Country', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='client_county',
            field=models.CharField(blank=True, default='County', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='client_email',
            field=models.CharField(default='joe@bloggs.com', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='client_moblie',
            field=models.CharField(blank=True, default='01234 456789', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='client_phone',
            field=models.CharField(blank=True, default='01234 456789', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='client_postcode',
            field=models.CharField(blank=True, default='XX00 0XX ', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='client_town',
            field=models.CharField(blank=True, default='Town', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_subtitle',
            field=models.CharField(blank=True, default='Get in contact', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_title',
            field=models.CharField(blank=True, default='Contact', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='custom_css',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='custom_html',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='custom_javacript',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='enumerated_list_header',
            field=models.CharField(blank=True, default='Approach', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='enumerated_list_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_info',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_info_title',
            field=models.CharField(blank=True, default='About', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='icon_list_header',
            field=models.CharField(blank=True, default='Services', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='image_gallery_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='image_gallery_title',
            field=models.CharField(default='Gallery', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_video_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='medium_blog_display_limit',
            field=models.IntegerField(blank=True, default=6),
        ),
        migrations.AddField(
            model_name='homepage',
            name='medium_username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='primary_colour',
            field=colorfield.fields.ColorField(default='#f37e77', max_length=18),
        ),
        migrations.AddField(
            model_name='homepage',
            name='second_blurb_background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='second_blurb_buttonText',
            field=models.CharField(blank=True, default='Find out more', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='second_blurb_header',
            field=models.CharField(blank=True, default='Blurb 2', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='second_blurb_subheader',
            field=models.CharField(blank=True, default='My Second Blurb 2', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='second_blurb_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_blurb',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_blurb_in_navigation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_contact_form',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_contact_in_navigation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_enumerated_list_in_navigation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_gallery_in_navigation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_icon_list_in_navigation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_second_blurb',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_second_blurb_in_navigation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_testimonials_in_navigation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='homepage',
            name='testimonials_header',
            field=models.CharField(blank=True, default='Testimonials', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='third_blurb_background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='third_blurb_header',
            field=models.CharField(blank=True, default='Blurb', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='third_blurb_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='third_blurb_subheader',
            field=models.CharField(blank=True, default='this is a blurb', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='third_blurb_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='third_show_blurb',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='video_background_brightness',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='client_firstname',
            field=models.CharField(blank=True, default='Joe', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='client_organisationName',
            field=models.CharField(blank=True, default='My Company', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='client_surname',
            field=models.CharField(blank=True, default='Blogs', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='intro_continue_button_text',
            field=models.CharField(blank=True, default='Continue', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='intro_header',
            field=models.CharField(default='Welcome to our website!', max_length=50),
        ),
        migrations.CreateModel(
            name='testimonialOrderable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonialOrderable', to='home.HomePage')),
                ('testimonialItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.testimonialItem')),
            ],
            options={
                'verbose_name': 'Testimonial List item',
                'verbose_name_plural': 'Testimonial List items',
            },
        ),
        migrations.CreateModel(
            name='socialMediaOrderable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='socialMediaOrderable', to='home.HomePage')),
                ('socialMediaItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.socialMediaItem')),
            ],
            options={
                'verbose_name': 'Social Media item',
                'verbose_name_plural': 'Social Media items',
            },
        ),
        migrations.CreateModel(
            name='iconListOrderable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('iconItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.iconItem')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='iconListOrderable', to='home.HomePage')),
            ],
            options={
                'verbose_name': 'Icon List item',
                'verbose_name_plural': 'Icon List items',
            },
        ),
        migrations.CreateModel(
            name='galleryOrderable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.gallery')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleryOrderable', to='home.HomePage')),
            ],
            options={
                'verbose_name': 'gallery item',
                'verbose_name_plural': 'gallery items',
            },
        ),
        migrations.CreateModel(
            name='enumeratedListOrderable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('enumeratedList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.enumeratedList')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='enumeratedListOrderable', to='home.HomePage')),
            ],
            options={
                'verbose_name': 'Enumerated List item',
                'verbose_name_plural': 'Enumerated List items',
            },
        ),
        migrations.CreateModel(
            name='carouselOrderable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='carouselOrderable', to='home.HomePage')),
            ],
            options={
                'verbose_name': 'carousel item',
                'verbose_name_plural': 'carousel items',
            },
        ),
    ]
