# Generated by Django 2.2.3 on 2020-04-13 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_favicon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryorderable',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='galleryorderable',
            name='page',
        ),
        migrations.AlterModelOptions(
            name='enumeratedlistorderable',
            options={'verbose_name': 'Panel item', 'verbose_name_plural': 'Panel items'},
        ),
        migrations.AlterModelOptions(
            name='iconlistorderable',
            options={'verbose_name': 'Tall panel item', 'verbose_name_plural': 'Tall panel items'},
        ),
        migrations.DeleteModel(
            name='carouselOrderable',
        ),
        migrations.DeleteModel(
            name='galleryOrderable',
        ),
    ]
