# Generated by Django 2.2.3 on 2020-04-13 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200413_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='show_blurb_in_navigation',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='show_contact_in_navigation',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='show_enumerated_list_in_navigation',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='show_gallery_in_navigation',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='show_icon_list_in_navigation',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='show_second_blurb_in_navigation',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='show_testimonials_in_navigation',
        ),
    ]
