# Generated by Django 2.2.3 on 2020-04-13 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200414_0002'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gallery',
        ),
    ]
