# Generated by Django 2.2 on 2020-04-15 21:18

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0008_contentpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featurespage',
            name='page_title',
        ),
        migrations.RemoveField(
            model_name='pricingpage',
            name='page_title',
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='featurespage',
            name='features_blurb_background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='featurespage',
            name='features_blurb_header',
            field=models.CharField(blank=True, default='Blurb', max_length=50),
        ),
        migrations.AddField(
            model_name='featurespage',
            name='features_blurb_subheader',
            field=models.CharField(blank=True, default='this is a blurb', max_length=50),
        ),
        migrations.AddField(
            model_name='featurespage',
            name='features_blurb_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='featurespage',
            name='features_show_blurb',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='featurespage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='pricingpage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.CreateModel(
            name='pricingIconListOrderable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('iconItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.iconItem')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricingIconListOrderable', to='home.PricingPage')),
            ],
            options={
                'verbose_name': 'Tall panel item',
                'verbose_name_plural': 'Tall panel items',
            },
        ),
        migrations.CreateModel(
            name='FeaturesEnumeratedListOrderable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('enumeratedList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.enumeratedList')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='FeaturesEnumeratedListOrderable', to='home.FeaturesPage')),
            ],
            options={
                'verbose_name': 'Panel item',
                'verbose_name_plural': 'Panel items',
            },
        ),
    ]
