# Generated by Django 2.2 on 2020-04-15 21:57

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200415_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='featuresIconListOrderable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('iconItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.iconItem')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='featuresIconListOrderable', to='home.FeaturesPage')),
            ],
            options={
                'verbose_name': 'Panel item',
                'verbose_name_plural': 'Panel items',
            },
        ),
        migrations.CreateModel(
            name='PricingEnumeratedListOrderable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('enumeratedList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.enumeratedList')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='PricingEnumeratedListOrderable', to='home.PricingPage')),
            ],
            options={
                'verbose_name': 'Panel item',
                'verbose_name_plural': 'Panel items',
            },
        ),
        migrations.RemoveField(
            model_name='pricingiconlistorderable',
            name='iconItem',
        ),
        migrations.RemoveField(
            model_name='pricingiconlistorderable',
            name='page',
        ),
        migrations.AlterModelOptions(
            name='iconlistorderable',
            options={'verbose_name': 'Panel item', 'verbose_name_plural': 'Panel items'},
        ),
        migrations.DeleteModel(
            name='FeaturesEnumeratedListOrderable',
        ),
        migrations.DeleteModel(
            name='pricingIconListOrderable',
        ),
    ]
