# Generated by Django 2.2 on 2020-04-15 22:34

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200415_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurespage',
            name='intro_content',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
