# Generated by Django 2.2 on 2020-04-15 22:49

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_featurespage_intro_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingpage',
            name='intro_content',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
