# Generated by Django 2.2 on 2020-04-15 23:18

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_pricingpage_intro_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='qaList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=120)),
                ('answer', models.CharField(max_length=5000)),
            ],
        ),
        migrations.AddField(
            model_name='pricingpage',
            name='question_and_answers_intro',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.CreateModel(
            name='qAOrderable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='qAOrderable', to='home.PricingPage')),
                ('qaList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.qaList')),
            ],
            options={
                'verbose_name': 'Q&A item',
                'verbose_name_plural': 'Q&A items',
            },
        ),
    ]
