# Generated by Django 2.2 on 2020-04-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20200415_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='client_phone_availability',
            field=models.CharField(blank=True, default='01234 456789', max_length=100),
        ),
    ]
