# Generated by Django 2.2 on 2020-04-18 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0014_homepage_client_phone_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='client_phone_availability',
            field=models.CharField(blank=True, default='Mon to Fri 9am to 6pm', max_length=100),
        ),
    ]
